version: '3.8'

services:
  bookstore:
    image: app:latest
    build: .
    ports:
      - "8080"
    environment:
      - DB_URL=${DB_URL:-jdbc:postgresql://db:5432/bookstore}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    depends_on:
      - db
      - localstack

  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
