server:
  port: 8080
spring:
  application:
    name: online-book-store

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookstore}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: true